steps:
# Install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
# Test
- name: 'gcr.io/$PROJECT_ID/ng'
  args: ['test']
# Build
- name: 'gcr.io/$PROJECT_ID/ng'
  args: ['build', '--prod']
# Deploy
- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy']
